name: All Contributors

on:
  push:
    branches: 
      - main
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true
      
jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JoshuaKGoldberg/all-contributors-auto-action@v0.5.0
