name: Npm Publish Utils

on:
  workflow_call:
    secrets:
      npm-token:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    if: startsWith(github.ref_type, 'tag')
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.target_commitish }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
      - run: npm install --force
      - run: npm run build
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.npm-token }}
          access: public
          provenance: true
